### ISSUE TITLE
music.163.com not scrobbling

### ISSUE THREAD

**Issue by pandap** [david-sabata/web-scrobbler#1297]
music.163.com not scrobbing
### Expected Behavior

scrobbing music when music playing
### Possible Solution

web server changed
### Steps to Reproduce (for bugs)

1.  
2.  
3.  

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser Name and version:

**Comment by alexesprit** [comment]
This is already fixed.

**Comment by pandap** [comment]
![image](https://cloud.githubusercontent.com/assets/5292261/25554661/2d0f4a86-2d05-11e7-9d41-49f31a4f7c5b.png)
im sorry, my chrome still have the problem

**Comment by pandap** [comment]
thanks
