### ISSUE TITLE
not scrobbling from rockradio.com

### ISSUE THREAD

**Issue by SeleniaIrisha** [david-sabata/web-scrobbler#1317]
![cm0dkt8vta0](https://cloud.githubusercontent.com/assets/28702358/26105379/6b9eac90-3a4a-11e7-9b0f-e46692183ee5.jpg)
![dwvvybee2kg](https://cloud.githubusercontent.com/assets/28702358/26105381/6be26b60-3a4a-11e7-8b01-d14e7215b805.jpg)
![vfcb30paike](https://cloud.githubusercontent.com/assets/28702358/26105380/6bc03306-3a4a-11e7-8173-2dd30eb2d92b.jpg)

**Comment by alexesprit** [comment]
Why did you open the issue again? I already fixed it.

**Comment by SeleniaIrisha** [comment]
Nothing that new screenshots? Scroobler still does not work. I do not know what you fixed.

**Comment by alexesprit** [comment]
Have you tried to install the extension from the latest master branch?

**Comment by SeleniaIrisha** [comment]
Yes. It still does not work.

**Comment by alexesprit** [comment]
Strange, it works for me. Could you provide the extension logs? [How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by SeleniaIrisha** [comment]
chrome.storage.local.LastFM = {
  "sessionID": "xxxxxAVTVcK-Jqm7N-BCX4UK16RCL-MJ",
  "sessionName": "Selenia_Irisha",
  "token": null
}
chromeStorage.js:102 chrome.storage.local.Core = {
  "appVersion": "1.64.0"
}
inject.js:33 -- loaded for the first time, injecting the scripts
inject.js:55 	injecting vendor/jquery-2.1.0.min.js
inject.js:55 	injecting core/content/reactor.js
inject.js:55 	injecting core/content/filter.js
inject.js:55 	injecting core/content/util.js
inject.js:55 	injecting core/content/connector.js
inject.js:55 	injecting connectors/radiotunes.js
inject.js:55 	injecting core/content/starter.js
controller.js:396 Tab 55: created controller for connector: {"label":"RockRadio","matches":["*://www.rockradio.com/*"],"js":["connectors/radiotunes.js"]}
inject.js:33 -- loaded for the first time, injecting the scripts
inject.js:55 	injecting vendor/jquery-2.1.0.min.js
inject.js:55 	injecting core/content/reactor.js
inject.js:55 	injecting core/content/filter.js
inject.js:55 	injecting core/content/util.js
inject.js:55 	injecting core/content/connector.js
inject.js:55 	injecting connectors/radiotunes.js
inject.js:55 	injecting core/content/starter.js
controller.js:396 Tab 39: created controller for connector: {"label":"RadioTunes","matches":["*://www.radiotunes.com/*"],"js":["connectors/radiotunes.js"]}
inject.js:33 -- loaded for the first time, injecting the scripts
inject.js:55 	injecting vendor/jquery-2.1.0.min.js
inject.js:55 	injecting core/content/reactor.js
inject.js:55 	injecting core/content/filter.js
inject.js:55 	injecting core/content/util.js
inject.js:55 	injecting core/content/connector.js
inject.js:55 	injecting connectors/vk.js
inject.js:55 	injecting core/content/starter.js
controller.js:396 Tab 41: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
inject.js:33 -- loaded for the first time, injecting the scripts
inject.js:55 	injecting vendor/jquery-2.1.0.min.js
inject.js:55 	injecting core/content/reactor.js
inject.js:55 	injecting core/content/filter.js
inject.js:55 	injecting core/content/util.js
inject.js:55 	injecting core/content/connector.js
inject.js:55 	injecting connectors/vk.js
inject.js:55 	injecting core/content/starter.js
controller.js:396 Tab 43: created controller for connector: {"label":"VK","matches":["*://vk.com/*"],"js":["connectors/vk.js"]}
inject.js:68 -- subsequent ajax navigation, the scripts are already injected

**Comment by SeleniaIrisha** [comment]
![frgpkwich78](https://cloud.githubusercontent.com/assets/28702358/26118101/52a8fdea-3a71-11e7-8d72-f571f9227ef7.jpg)
![npvymmwp1fw](https://cloud.githubusercontent.com/assets/28702358/26118100/52a5b87e-3a71-11e7-8082-47251e53ca99.jpg)

**Comment by alexesprit** [comment]
Could you install the extension from this zip https://github.com/alexesprit/web-scrobbler/archive/radiotunes.zip and tell if something changes?

**Comment by SeleniaIrisha** [comment]
We have two users, so there are actually two browsers. The one where installed from the archive, works. Installed from the store does not work.
![1](https://cloud.githubusercontent.com/assets/28702358/26119337/8d7017c0-3a75-11e7-82e1-4e72f33b24ff.jpg)
![2](https://cloud.githubusercontent.com/assets/28702358/26119338/8d8b8cf8-3a75-11e7-84c9-28d4ccb9eccb.jpg)

**Comment by alexesprit** [comment]
The extension from the Chrome Web Store is supposed to be broken, I haven't update it yet.

**Comment by SeleniaIrisha** [comment]
Yes. Thank you!
