### ISSUE TITLE
Google Play Music redesign breaks info retrieval.

### ISSUE THREAD

**Issue by TheQwerty** [david-sabata/web-scrobbler#602]
The track title is now in `div#player-song-title`.
The play/pause button element has changed from `button` to `sg-icon-button` resulting in `#player sj-icon-button[data-id="play-pause"]`.

At first glance the other selectors in `googlemusic.js` and `v2/googlemusic.js` seem to still be okay, but I'm not sure what else should be checked.

**Comment by munframed** [comment]
I really hope to see it fixed... Google music is my primary way to listen to music and now it doesn't scrobble :(

**Comment by david-sabata** [comment]
Yep, I'm aware of that and will fix ASAP

I like the redesign btw :)

**Comment by futchadoc** [comment]
Thanks - came here to report but glad to see you're already working on it!

**Comment by tjharman** [comment]
I came here to say what futchadoc said but he's said it already.

**Comment by futchadoc** [comment]
I'm listening to Pandora like a peasant because I gotta have my scrobbles :D

**Comment by beanoboo** [comment]
Same here. Thanks, dude!

**Comment by VladimirAmiorkov** [comment]
I really love web-scrobbler thank you for developing it and adding future support for it.

**Comment by kmehlin** [comment]
Came to report, but as always...you're on it! Keep up the good work.

**Comment by aleksijuvani** [comment]
Oh, that's some fast action. Thanks dude!

**Comment by carluri** [comment]
Redesign is awesome, and thanks for working on this

**Comment by naimahm** [comment]
I agree with all the other comments. Loving redesign. And thank you very much for development of this  :)

**Comment by StaticSpine** [comment]
Hey! 

Thanks a lot for working on scrobbler! I'm looking forward to this issue to be fixed. 

Good luck!

**Comment by olls** [comment]
:D Thank you!

**Comment by futchadoc** [comment]
Since this issue has been fixed, my music is scrobbling, but it's no longer scrobbling the album data. has anyone else experienced this?

**Comment by markjustin** [comment]
Yeah futchadoc, I've created a pull request that fixes the album data too https://github.com/david-sabata/web-scrobbler/pull/608

**Comment by toddgrotenhuis** [comment]
Hrm. Mine is still not scrobbling. Did others have to do anything differently?

**Comment by brycied00d** [comment]
@toddgrotenhuis Have you confirmed in chrome://extensions/ that you have version 1.47 of the extension? It "just worked" for me once Chrome had updated the extension (just double-checked and it's working for me as I type this.)

**Comment by toddgrotenhuis** [comment]
@brycied00d Yes, running 1.47.
