### ISSUE TITLE
Google Play Music has been updated and is no longer scrobbling. 

### ISSUE THREAD

**Issue by aalanmr** [david-sabata/web-scrobbler#605]
The Google Play Music website has a new interface and now the last.fm scrobbler isn't recognizing when songs are playing, it needs to be updated also. 

Thank you :)

**Comment by olls** [comment]
This should be fixed now #602

**Comment by aalanmr** [comment]
Thank you very much! :)



Sent by Outlook for Android





On Sat, May 16, 2015 at 2:55 PM -0700, "Oliver Faircliff" <notifications@github.com> wrote:
This should be fixed now #602

---

**Comment by eocsor** [comment]
It's only partially fixed. Songs played from Google Play Music website using version 1.47 are successfully scrobbled to Last.fm but as stand-alone tracks, not linked to the appropriate album.

**Comment by markjustin** [comment]
@eocsor I've made a pull request that fixes this: https://github.com/david-sabata/web-scrobbler/pull/608

**Comment by david-sabata** [comment]
The album scrobbling should be fixed now too.
