### ISSUE TITLE
Google Play Music "the song was not recognized"

### ISSUE THREAD

**Issue by vanessacursino** [david-sabata/web-scrobbler#864]
The extension doesn't recognize any song played. "The song was not recognize"

**Comment by hluk** [comment]
I had the same issue. The track name fetched from Google Play Music was always empty.

PR #848 fixed that for me (thanks to @TheQwerty).

**Comment by nbackas** [comment]
This still is an issue for me

**Comment by eldonzo** [comment]
Me too.

Is #848 live in the Chrome Web Store version? My actual version is 1.54

**Comment by hluk** [comment]
It's not yet in any version.

**Comment by eldonzo** [comment]
Ok I'll wait then, thanks.

**Comment by inverse** [comment]
Should be fixed when the next release is released to the store. Alternatively run unpacked from master.

**Comment by tomg555** [comment]
Still happening here

**Comment by dzek69** [comment]
still not working, jesus.

can anyone make a fork with all fixes applied? david seems to be very busy

**Comment by illmoded** [comment]
still getting -null as title

**Comment by jlewin** [comment]
Like others, wasn't working with the latest Chrome Web Store version. Spent a few minutes to disable the published extension, cloned the repo and created a new unpacked extension. After 3 minutes of work it's back to Scrobbling again.

**Comment by david-sabata** [comment]
This is already fixed in master and will be released soon
