### ISSUE TITLE
Not scrobbling from 8tracks

### ISSUE THREAD

**Issue by ajakidjo** [david-sabata/web-scrobbler#943]
For international users, they've changed the songs to play on Youtube instead. But they don't scrobble at all. What to do?

**Comment by inverse** [comment]
Is it completely broken or just for the YouTube tracks?

**Comment by ajakidjo** [comment]
I think it does scrobble some of the tracks that do show up but it doesn't scrobble the Youtube tracks at all.

**Comment by inverse** [comment]
I fixed the YT side of things with hopefully out impacting the rest. Do you have any playlists with mixed content? e.g. from YT and 8track itself?

**Comment by ajakidjo** [comment]
Sorry I'm late. 

I checked but it's still not scrobbling any of the Youtube videos on the site. Unfortunately one can only play either tracks or videos.

**Comment by inverse** [comment]
I mean fixed in my pull request. Are you able to try running the extension unpacked? See: https://github.com/david-sabata/web-scrobbler#unpacked-extension

Using the contents of this zip https://github.com/inverse/web-scrobbler/archive/8track-fix.zip

**Comment by ajakidjo** [comment]
Tried it. It's not working either.

**Comment by inverse** [comment]
Hmm, there's def still a bug with it. It's working when I do a full refresh when on a playlist, but not with the initial visit. Something to do with the page change I guess.

**Comment by alexesprit** [comment]
Is it still an issue? Scrobbling from 8tracks works fine for me.

**Comment by alexesprit** [comment]
I fixed 8tracks connector in 2886aa8d0ec444c867520432f4fcb1ce47d215b3 and df5ddfbd712df11d35c201c4d4497cff44e430b0. Should work fine for both players.
